# PROFILES
# dev | test | prod
spring:
  profiles:
    active: local


server:
  tomcat:
    max-threads: 10
  port: 8080




---

spring:
  profiles: local
  datasource:
      url: jdbc:mysql://localhost:3306/iop-meta?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      maxActive: 10
      initialSize: 1
      maxWait: 6000
      minIdle: 1
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

